### ISSUE TITLE
API: Aufstellungen von außen setzen

### ISSUE THREAD

**Issue by Sollunad** [Sollunad/RaidOrgaPlus#414]
Neuer Entrypoint `/api`, Endpoint POST `/api/aufstellungen`

Request-Body: 
```
{
    auth: <gültige Session-ID aus Login mit Raidleiter-Rechten für entsprechenden Raid>
    body: Beispiel siehe unten
}
```

```
{
    terminId: 123
    aufstellungen: [
        {
            aufstellungId?: 1234
            bossId?: 12
            isCM?: true / false
            positionen: [
                {
                    position: 1
                    spielerId: 12
                    classId: 20
                    roleId: 5
                }
            ]
        }
    ]
}
```

Wenn einer bereits existierenden Aufstellung Elemente hinzugefügt werden, muss die `aufstellungId` übergeben werden und `bossId` wird auf null gesetzt. Soll eine neue Aufstellung im Termin erzeugt werden, wird `aufstellungId` als null gesetzt und stattdessen die `bossId` gesetzt. Neu angelegte Aufstellungen werden in der angegebenen Reihenfolge erzeugt.

Werden sowohl `aufstellungId` als auch `bossId` angegeben, wird die `bossId` ignoriert.

`position` ist ein Wert zwischen 1 und 10 und beschreibt die Stelle innerhalb der Aufstellung in read-order (oben links, dann oben rechts)

`classId`: [Link](https://user-images.githubusercontent.com/20877740/87849830-f61a2600-c8eb-11ea-97d3-fd27051505d8.png)

`roleId`: [Link](https://user-images.githubusercontent.com/20877740/87849845-1e098980-c8ec-11ea-9762-7ef0c30fd2bc.png)

**Comment by ProfBits** [comment]
session muss in auth geänderd werden, damit es zu dem bestehenden system passt
