### ISSUE TITLE
Aufstellung: Rolle kann nicht auf default Zurück gesetzt werden

### ISSUE THREAD

**Issue by ProfBits** [Sollunad/RaidOrgaPlus#419]
Wenn man in einer Aufstellung einer Personn eine Rolle (Power, Healer, ...) zugeweißen hat und man diese mit rechtscklick wieder entfernt wird das nicht am Server übernommen -> F5 und der Eintrag ist wieder da.

**Comment by Sollunad** [comment]
Danke für's Einstellen!
